### ISSUE TITLE
lola.svg seems wrong

### ISSUE THREAD

**Issue by chenchenrui** [loicland/img2svg#2]
I changed cp_kmpp_d0_dist to cp_d0_dist because cp_kmpp_d0_dist does not exist in the code you provided.But when I run python img2svg.py,the resuld is not correct.
![image](https://github.com/loicland/img2svg/assets/115409374/39331234-8a5b-4fe8-8762-231b4efe3720)
Would you mind taking a look and letting me know if I misunderstood or made any mistakes? I'd greatly appreciate your guidance on this.
Thank you very much for your help!

255.0
Reading image of size 1087 by 1149 with 3 channels
Cut-pursuit initialization:
        1 connected component(s), 0 saturated, and 1 reduced edge(s).

Cut-pursuit iteration 1 (max. 10):
        Split... 9541 new activated edge(s).
        Compute connected components... 8 connected component(s), 0 saturated.
        Compute reduced graph... 11 reduced edge(s).
        Solve reduced problem:
        Merge... 0 deactivated edge(s).
        relative iterate evolution 6.29e-02 (tol. 1.00e-02)
        8 connected component(s), 0 saturated, and 11 reduced edge(s).

Cut-pursuit iteration 2 (max. 10):
        Split... 4038 new activated edge(s).
        Compute connected components... 11 connected component(s), 6 saturated.
        Compute reduced graph... 14 reduced edge(s).
        Solve reduced problem:
        Merge... 3720 deactivated edge(s).
        relative iterate evolution 1.55e-02 (tol. 1.00e-02)
        10 connected component(s), 5 saturated, and 12 reduced edge(s).

Cut-pursuit iteration 3 (max. 10):
        Split... 0 new activated edge(s).
        relative iterate evolution 0.00e+00 (tol. 1.00e-02)
        10 connected component(s), 10 saturated, and 12 reduced edge(s).

Partition done.
Vectorization done.

**Comment by chenchenrui** [comment]
sorry，I succeed now

**Comment by loicland** [comment]
Hi, thanks for the issue.

What was the problem and how did you fix it?
