### ISSUE TITLE
Failure segmentation in grayscale images

### ISSUE THREAD

**Issue by ruomingzhai** [loicland/img2svg#3]
Hi, I encountered an wired problem while segmenting a simple grayscale image.
Here is the image, which is supposed to detect the white area  but it failed:
original image:
![scene4_66](https://github.com/loicland/img2svg/assets/76636722/41f5e019-cbab-4d0a-a417-2499fcf1af59)

after segmented:
![scene4_66_morph](https://github.com/loicland/img2svg/assets/76636722/d5714de1-f4b3-401e-ae08-c137a4eb37d4)
However, when I vertically flip the image like this:
![scene4_66_morph_filp](https://github.com/loicland/img2svg/assets/76636722/8bb8c737-7334-424d-b8a8-ea8236735afb)
It works and the image are segmented into two component like this:
![scene4_66_morph_filp](https://github.com/loicland/img2svg/assets/76636722/1caf2b4d-2e1e-46a5-9bbf-27e5bff484e8)

I don't know why this happen, and hope you can give me some clues.

**Comment by loicland** [comment]
I downloaded your images, and was able to segment them both:

![bar](https://github.com/loicland/img2svg/assets/1902679/d6fe1ae6-53eb-47f5-9c5a-ef559dd16549)

```
$ python img2svg.py -f bar.jpg -lc r

Reading image of size 47 by 92 with 3 channels
Cut-pursuit initialization:
	1 connected component(s), 0 saturated, and at most 1 reduced edge(s).

Cut-pursuit iteration 1 (max. 10): 
	Split... 1599 new activated edge(s).
	Compute connected components... 21 connected component(s), 0 saturated.
	Compute reduced graph... 60 reduced edge(s).
	Solve reduced problem: 
	Merge... 1026 deactivated edge(s).
	relative iterate evolution 4.31e+03 (tol. 1.00e-02)
	1 connected component(s), 0 saturated, and at most 0 reduced edge(s).

Cut-pursuit iteration 2 (max. 10): 
	Split... 932 new activated edge(s).
	Compute connected components... 22 connected component(s), 0 saturated.
	Compute reduced graph... 54 reduced edge(s).
	Solve reduced problem: 
	Merge... 899 deactivated edge(s).
	relative iterate evolution 4.27e+03 (tol. 1.00e-02)
	2 connected component(s), 0 saturated, and at most 29 reduced edge(s).

Cut-pursuit iteration 3 (max. 10): 
	Split... 0 new activated edge(s).
	relative iterate evolution 0.00e+00 (tol. 1.00e-02)
	2 connected component(s), 2 saturated, and at most 29 reduced edge(s).

Partition done.
Vectorization done.
```
 (although the image is flipped for some reason)
![bar](https://github.com/loicland/img2svg/assets/1902679/f3622fd3-9815-4ce2-adfe-882eb4676041)


![bar2](https://github.com/loicland/img2svg/assets/1902679/9a5bab36-cc2f-42af-9a15-8a32db8dab65)

```
Reading image of size 47 by 92 with 3 channels
Cut-pursuit initialization:
	1 connected component(s), 0 saturated, and at most 1 reduced edge(s).

Cut-pursuit iteration 1 (max. 10): 
	Split... 1599 new activated edge(s).
	Compute connected components... 21 connected component(s), 0 saturated.
	Compute reduced graph... 60 reduced edge(s).
	Solve reduced problem: 
	Merge... 1026 deactivated edge(s).
	relative iterate evolution 4.31e+03 (tol. 1.00e-02)
	1 connected component(s), 0 saturated, and at most 0 reduced edge(s).

Cut-pursuit iteration 2 (max. 10): 
	Split... 932 new activated edge(s).
	Compute connected components... 22 connected component(s), 0 saturated.
	Compute reduced graph... 54 reduced edge(s).
	Solve reduced problem: 
	Merge... 899 deactivated edge(s).
	relative iterate evolution 4.27e+03 (tol. 1.00e-02)
	2 connected component(s), 0 saturated, and at most 29 reduced edge(s).

Cut-pursuit iteration 3 (max. 10): 
	Split... 0 new activated edge(s).
	relative iterate evolution 0.00e+00 (tol. 1.00e-02)
	2 connected component(s), 2 saturated, and at most 29 reduced edge(s).

Partition done.
Vectorization done.
```
![bar2](https://github.com/loicland/img2svg/assets/1902679/53a4c465-6289-40ef-bad3-474112f6d9bb)

Can you post the details of the run?

**Comment by ruomingzhai** [comment]
I edit several default values of optimization parameters in img2svg like this:
<img width="871" alt="result" src="https://github.com/loicland/img2svg/assets/76636722/2a06aa12-1b02-4769-b1d5-b98a91123925">

 I need straight lines but not Bezier curves, so I set smooth to zero.

**Comment by loicland** [comment]
you really should not change the default values in the file, but pass parameters in command line.
For example here you apply the log function to the inputs, which really doesn't not seem like a good idea for a binary image. I also can't help you debug if I don't know the values of all parameters.

My advice is: get a fresh clone, and just set `-s 0`, this works for me.

**Comment by ruomingzhai** [comment]
I used the original image and the output info shows:

255.0
Reading image of size 88 by 43 with 3 channels
Cut-pursuit initialization:
	1 connected component(s), 0 saturated, and at most 1 reduced edge(s).

Cut-pursuit iteration 1 (max. 10): 
	Split... 1327 new activated edge(s).
	Compute connected components... 17 connected component(s), 0 saturated.
	Compute reduced graph... 43 reduced edge(s).
	Solve reduced problem: 
	Merge... 755 deactivated edge(s).
	relative iterate evolution 4.83e+03 (tol. 1.00e-02)
	1 connected component(s), 0 saturated, and at most 0 reduced edge(s).

Cut-pursuit iteration 2 (max. 10): 
	Split... 643 new activated edge(s).
	Compute connected components... 17 connected component(s), 0 saturated.
	Compute reduced graph... 39 reduced edge(s).
	Solve reduced problem: 
	Merge... 623 deactivated edge(s).
	relative iterate evolution 4.76e+03 (tol. 1.00e-02)
	1 connected component(s), 0 saturated, and at most 0 reduced edge(s).

Cut-pursuit iteration 3 (max. 10): 
	Split... 142 new activated edge(s).
	Compute connected components... 4 connected component(s), 0 saturated.
	Compute reduced graph... 6 reduced edge(s).
	Solve reduced problem: 
	Merge... 139 deactivated edge(s).
	relative iterate evolution 1.04e+00 (tol. 1.00e-02)
	1 connected component(s), 0 saturated, and at most 0 reduced edge(s).

Cut-pursuit iteration 4 (max. 10): 
	Split... 0 new activated edge(s).
	relative iterate evolution 0.00e+00 (tol. 1.00e-02)
	1 connected component(s), 1 saturated, and at most 0 reduced edge(s).

Partition done.
Vectorization done.

-------------------------------------------------------------------------------------
Then I download the image you post in your review, and it works but the image col and row are opposite with mine:

Reading image of size 47 by 92 with 3 channels
Cut-pursuit initialization:
	1 connected component(s), 0 saturated, and at most 1 reduced edge(s).

Cut-pursuit iteration 1 (max. 10): 
	Split... 1412 new activated edge(s).
	Compute connected components... 17 connected component(s), 0 saturated.
	Compute reduced graph... 46 reduced edge(s).
	Solve reduced problem: 
	Merge... 844 deactivated edge(s).
	relative iterate evolution 4.34e+03 (tol. 1.00e-02)
	1 connected component(s), 0 saturated, and at most 0 reduced edge(s).

Cut-pursuit iteration 2 (max. 10): 
	Split... 904 new activated edge(s).
	Compute connected components... 18 connected component(s), 0 saturated.
	Compute reduced graph... 43 reduced edge(s).
	Solve reduced problem: 
	Merge... 866 deactivated edge(s).
	relative iterate evolution 4.14e+03 (tol. 1.00e-02)
	2 connected component(s), 0 saturated, and at most 21 reduced edge(s).

Cut-pursuit iteration 3 (max. 10): 
	Split... 0 new activated edge(s).
	relative iterate evolution 0.00e+00 (tol. 1.00e-02)
	2 connected component(s), 2 saturated, and at most 21 reduced edge(s).

Partition done.
Vectorization done.

**Comment by loicland** [comment]
There is a number just above "Reading image of size 47 by 92 with 3 channels" in your second run, can you report it? Also, is this with all default parameters?

**Comment by ruomingzhai** [comment]
Sorry, the number is just the printing value for img.max() and it have nothing to do with my problem.
It is wired that I used the image downloaded from your reply and it works too. But it really failed in my raw image. Here is my image file. Can you try it out?
![scene4_66_morph](https://github.com/loicland/img2svg/assets/76636722/33eeddf6-129c-41cf-bc84-fc550cb64f5b)

**Comment by ruomingzhai** [comment]
[scene4_66_morph.zip](https://github.com/loicland/img2svg/files/14974911/scene4_66_morph.zip)
Here is the zip file, I am afraid the previous image may turn into a successful segmented image because the website may has changed its image format.

**Comment by loicland** [comment]
> Sorry, the number is just the printing value for img.max() and it have nothing to do with my problem.

I know, and I think it may actually be very related to your problem: different bit depth elads to different max values. Can you report it?

**Comment by ruomingzhai** [comment]
> > Sorry, the number is just the printing value for img.max() and it have nothing to do with my problem.
> 
> I know, and I think it may actually be very related to your problem: different bit depth elads to different max values. Can you report it?

You mean to report the codes?  I just add the print code as follows:
![image](https://github.com/loicland/img2svg/assets/76636722/46e704c8-f220-44f3-9dc1-3e4ae9d0fb0f)


and the printing info as follows:
------------------------------------------------------------------------------------
255.0
Reading image of size 43 by 88 with 3 channels
Cut-pursuit initialization:
	1 connected component(s), 0 saturated, and at most 1 reduced edge(s).

Cut-pursuit iteration 1 (max. 10): 
	Split... 1433 new activated edge(s).
	Compute connected components... 18 connected component(s), 0 saturated.
	Compute reduced graph... 46 reduced edge(s).
	Solve reduced problem: 
	Merge... 868 deactivated edge(s).
	relative iterate evolution 2.27e+04 (tol. 1.00e-02)
	1 connected component(s), 0 saturated, and at most 0 reduced edge(s).

Cut-pursuit iteration 2 (max. 10): 
	Split... 783 new activated edge(s).
	Compute connected components... 17 connected component(s), 0 saturated.
	Compute reduced graph... 44 reduced edge(s).
	Solve reduced problem: 
	Merge... 742 deactivated edge(s).
	relative iterate evolution 2.24e+04 (tol. 1.00e-02)
	1 connected component(s), 0 saturated, and at most 0 reduced edge(s).

Cut-pursuit iteration 3 (max. 10): 
	Split... 0 new activated edge(s).
	relative iterate evolution 0.00e+00 (tol. 1.00e-02)
	1 connected component(s), 1 saturated, and at most 0 reduced edge(s).

Partition done.
Vectorization done.

**Comment by loicland** [comment]
Hi,

so the issue is the balancing cut, which is designed to accelerate the processing of large images, and seems to lead to very unoptimal splits on such small images. Deactivate this L111 of img2svg like this:

```
    comp, rX, dump = cp_kmpp_d0_dist(1,
        np.asfortranarray(img.reshape((args.n_ver, args.n_chan)).T), first_edge, adj_vertices,
        edge_weights=reg_strength * edg_weights, cp_it_max=10,
        cp_dif_tol=1e-2, max_num_threads=0, balance_parallel_split=False)
```


`python img2svg.py -f scene4.jpg -s 0 `

![scene4](https://github.com/loicland/img2svg/assets/1902679/d1cf6aac-60eb-446e-b391-dc198cec102b)

And in case what you want is to recover simple shapes, change the line break tolearance:

`python img2svg.py -f scene4.jpg -s 0 -lt 3`

![scene4](https://github.com/loicland/img2svg/assets/1902679/daec2902-5d9d-4544-9dfd-708bc20f2867)

**Comment by ruomingzhai** [comment]
Thanks a lot! It works after setting balance_parallel_split to False!
